using System.Text.Json.Serialization;
using System;
using System.Text.Json;
using System.Collections.Generic;
using System.Collections.Concurrent;
using NetworkMonitor.Objects;
using NetworkMonitor.Objects.Repository;
using NetworkMonitor.Objects.ServiceMessage;
using NetworkMonitor.Connection;
using NetworkMonitor.DTOs;
using NetworkMonitor.Service.Services.OpenAI;
namespace NetworkMonitor.Objects
{
  [JsonSourceGenerationOptions(WriteIndented = false)]
  [JsonSerializable(typeof(bool))]
  [JsonSerializable(typeof(Guid))]
  [JsonSerializable(typeof(int))]
  [JsonSerializable(typeof(List<int>))]
  [JsonSerializable(typeof(List<string>))]
  [JsonSerializable(typeof(Stack<string>))]
  [JsonSerializable(typeof(uint))]
  [JsonSerializable(typeof(short))]
  [JsonSerializable(typeof(ushort))]
  [JsonSerializable(typeof(float))]
  [JsonSerializable(typeof(double))]
  [JsonSerializable(typeof(string))]
  [JsonSerializable(typeof(object))]
  [JsonSerializable(typeof(DateTime))]
  [JsonSerializable(typeof(System.Object))]
  [JsonSerializable(typeof(System.Tuple<string, string>))]
  [JsonSerializable(typeof(PingParams))]
  [JsonSerializable(typeof(MLParams))]
  [JsonSerializable(typeof(List<MonitorIP>))]
  [JsonSerializable(typeof(MonitorIP))]
  [JsonSerializable(typeof(MonitorIPQuery))]
  [JsonSerializable(typeof(UpdateMonitorIP))]
  [JsonSerializable(typeof(List<MonitorPingInfo>))]
  [JsonSerializable(typeof(MonitorPingInfo))]
  [JsonSerializable(typeof(MonitorPingInfoQuery))]
  [JsonSerializable(typeof(SwapMonitorPingInfo))]
  [JsonSerializable(typeof(List<PingInfo>))]
  [JsonSerializable(typeof(PingInfo))]
  [JsonSerializable(typeof(NmapRequest))]
  [JsonSerializable(typeof(OpensslRequest))]
  [JsonSerializable(typeof(BusyboxRequest))]
  [JsonSerializable(typeof(MetasploitRequest))]
  [JsonSerializable(typeof(AddCmdProcessorRequest))]
  [JsonSerializable(typeof(HuggingFaceImageRequest))]
  [JsonSerializable(typeof(HuggingFaceImageData))]
  [JsonSerializable(typeof(List<HuggingFaceImageData>))]
  [JsonSerializable(typeof(HuggingFaceImageResponse))]
  [JsonSerializable(typeof(ImageRequest))]
  [JsonSerializable(typeof(ImageData))]
  [JsonSerializable(typeof(List<ImageData>))]
  [JsonSerializable(typeof(ImageResponse))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaImageRequest))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaImageRequestRoot))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaTaskResponse))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaFullResponse))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaImage))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaExtra))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaDebugInfo))]
  [JsonSerializable(typeof(NetworkMonitor.Service.Services.OpenAI.NovitaTask))]
  [JsonSerializable(typeof(HuggingFaceRequest))]
  [JsonSerializable(typeof(CreateIndexRequest))]
  [JsonSerializable(typeof(QueryIndexRequest))]
  [JsonSerializable(typeof(QueryResultObj))]
  [JsonSerializable(typeof(List<QueryResultObj>))]
  [JsonSerializable(typeof(RootObject))]
  [JsonSerializable(typeof(Event))]
  [JsonSerializable(typeof(NetworkMonitor.Objects.User))]
  [JsonSerializable(typeof(Info))]
  [JsonSerializable(typeof(TwoFactor))]
  [JsonSerializable(typeof(List<RemovePingInfo>))]
  [JsonSerializable(typeof(RemovePingInfo))]
  [JsonSerializable(typeof(List<UserInfo>))]
  [JsonSerializable(typeof(UserInfo))]
  [JsonSerializable(typeof(List<EmailInfo>))]
  [JsonSerializable(typeof(EmailInfo))]
  [JsonSerializable(typeof(List<StatusObj>))]
  [JsonSerializable(typeof(StatusObj))]
  [JsonSerializable(typeof(ProcessorConnectObj))]
  [JsonSerializable(typeof(SentUserData))]
  [JsonSerializable(typeof(SentDateData))]
  [JsonSerializable(typeof(ResultObj))]
  [JsonSerializable(typeof(List<RegisteredUser>))]
  [JsonSerializable(typeof(RegisteredUser))]
  [JsonSerializable(typeof(RabbitMQObj))]
  [JsonSerializable(typeof(ProcessorObj))]
  [JsonSerializable(typeof(List<ProcessorObj>))]
  [JsonSerializable(typeof(MonitorStatusAlert))]
  [JsonSerializable(typeof(PredictStatusAlert))]
  [JsonSerializable(typeof(List<MonitorStatusAlert>))]
  [JsonSerializable(typeof(List<PredictStatusAlert>))]
  [JsonSerializable(typeof(DetectionResult))]
  [JsonSerializable(typeof(PredictStatus))]
  [JsonSerializable(typeof(Messages))]
  [JsonSerializable(typeof(List<JsonBlogPost>))]
  [JsonSerializable(typeof(JsonBlogPost))]
  [JsonSerializable(typeof(EditHost))]
  [JsonSerializable(typeof(DelHost))]
  [JsonSerializable(typeof(Blog))]
  [JsonSerializable(typeof(BlogCategory))]
  [JsonSerializable(typeof(BlogPicture))]
  [JsonSerializable(typeof(AlertFlagObj))]
  [JsonSerializable(typeof(List<AlertFlagObj>))]
  [JsonSerializable(typeof(AlertMessage))]
  [JsonSerializable(typeof(CloudEvent))]
  [JsonSerializable(typeof(AgentUserFlow))]
  [JsonSerializable(typeof(MonitorMLCheckObj))]
  [JsonSerializable(typeof(MonitorMLInitObj))]
  [JsonSerializable(typeof(ProcessorQueueDicObj))]
  [JsonSerializable(typeof(ProcessorDataObj))]
  [JsonSerializable(typeof(ProcessorScanDataObj))]
  [JsonSerializable(typeof(FunctionRegistryReply))]
  [JsonSerializable(typeof(List<ProductObj>))]
  [JsonSerializable(typeof(ProductObj))]
  [JsonSerializable(typeof(ProcessorInitObj))]
  [JsonSerializable(typeof(ProcessorDataBuilder))]
  [JsonSerializable(typeof(ProcessorUserEventObj))]
  [JsonSerializable(typeof(ProcessorConnectObj))]
  [JsonSerializable(typeof(List<PaymentTransaction>))]
  [JsonSerializable(typeof(PaymentTransaction))]
  [JsonSerializable(typeof(PaymentServiceInitObj))]
  [JsonSerializable(typeof(MonitorServiceInitObj))]
  [JsonSerializable(typeof(FunctionCallData))]
  [JsonSerializable(typeof(Dictionary<string, object>))]
  [JsonSerializable(typeof(MonitorDataInitObj))]
  [JsonSerializable(typeof(LLMServiceObj))]
  [JsonSerializable(typeof(FunctionState))]
  [JsonSerializable(typeof(ChatServiceInitObj))]
  [JsonSerializable(typeof(AlertServiceInitObj))]
  [JsonSerializable(typeof(AlertServiceAlertObj))]
  [JsonSerializable(typeof(SystemParams))]
  [JsonSerializable(typeof(List<SystemUrl>))]
  [JsonSerializable(typeof(LoadServer))]
  [JsonSerializable(typeof(RabbitLoadServer))]
  [JsonSerializable(typeof(RabbitLoadServerResult))]
  [JsonSerializable(typeof(SystemUrl))]
  [JsonSerializable(typeof(ContentObject))]
  [JsonSerializable(typeof(ChatCompletion))]
  [JsonSerializable(typeof(ChatCompletionUsage))]
  [JsonSerializable(typeof(ChatCompletionChoice))]
  [JsonSerializable(typeof(ChatCompletionMessage))]
  [JsonSerializable(typeof(Message))]
  [JsonSerializable(typeof(List<UpdateProductObj>))]
  [JsonSerializable(typeof(UpdateProductObj))]
  [JsonSerializable(typeof(HostResponseObj))]
  [JsonSerializable(typeof(HostReportObj))]
  [JsonSerializable(typeof(DataFileObj))]
  [JsonSerializable(typeof(GenericEmailObj))]
  [JsonSerializable(typeof(NetConnectConfig))]
  [JsonSerializable(typeof(List<GenericEmailObj>))]
  [JsonSerializable(typeof(List<BlogList>))]
  [JsonSerializable(typeof(List<HostResponseObj>))]
  [JsonSerializable(typeof(System.Tuple<string, string>))]
  [JsonSerializable(typeof(TResultObj<string, string>))]
  [JsonSerializable(typeof(TResultObj<string>))]
  [JsonSerializable(typeof(TResultObj<int>))]
  [JsonSerializable(typeof(TResultObj<List<MonitorPingInfo>, SentUserData>))]
  [JsonSerializable(typeof(TResultObj<List<MonitorIP>, SentUserData>))]
  [JsonSerializable(typeof(TResultObj<List<MonitorPingInfo>>))]
  [JsonSerializable(typeof(TResultObj<List<MonitorIP>>))]
  [JsonSerializable(typeof(TResultObj<MonitorIP>))]
  [JsonSerializable(typeof(TResultObj<MonitorPingInfo>))]
  [JsonSerializable(typeof(TResultObj<ProductObj>))]
  [JsonSerializable(typeof(TResultObj<UserInfo>))]
  [JsonSerializable(typeof(TResultObj<List<ProductObj>>))]
  [JsonSerializable(typeof(TResultObj<List<PingInfoDTO>, SentUserData>))]
  [JsonSerializable(typeof(TResultObj<List<HostResponseObj>, SentUserData>))]
  [JsonSerializable(typeof(TResultObj<PingInfoDTO, SentUserData>))]
  [JsonSerializable(typeof(TResultObj<HostResponseObj, SentUserData>))]
  [JsonSerializable(typeof(TResultObj<ProcessorDataObj>))]
  [JsonSerializable(typeof(TResultObj<LoadServer>))]
  [JsonSerializable(typeof(TResultObj<RabbitLoadServer>))]
  [JsonSerializable(typeof(JsonElement))]


  internal partial class SourceGenerationContext : JsonSerializerContext
  {


  }
}